liip_imagine:
    driver: "gd"
    twig:
        mode: lazy
    filter_sets:
        slider:
            quality: 85
            filters:
                thumbnail: { size: [1920, 676], mode: outbound }
        breadcrumb:
            quality: 85
            filters:
                thumbnail: { size: [1920, 437], mode: outbound }
